# Generated by Django 3.2.5 on 2021-12-10 17:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='coorganisers',
            field=models.ManyToManyField(blank=True, related_name='coorganises', to=settings.AUTH_USER_MODEL),
        ),
    ]
