# Generated by Django 3.2.5 on 2021-12-10 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EloRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elo_rating', models.IntegerField(default=1000)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='has_elo_club', to='clubs.club')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_elo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
