# Generated by Django 3.2.5 on 2021-12-07 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubapplicationmodel',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
