# Generated by Django 3.2.5 on 2021-12-16 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='applicants',
        ),
    ]
