# Generated by Django 3.2.5 on 2021-12-12 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_elorating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='elo_rating',
        ),
        migrations.AlterField(
            model_name='elorating',
            name='elo_rating',
            field=models.IntegerField(),
        ),
    ]
