# Generated by Django 3.2.5 on 2021-11-21 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_remove_user_user_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_level',
            field=models.CharField(choices=[('Applicant', 'Applicant'), ('Member', 'Member'), ('Officer', 'Officer'), ('Owner', 'Owner')], default='Applicant', max_length=10),
        ),
    ]
