# Generated by Django 3.2.5 on 2021-11-26 23:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_clubapplicationmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubapplicationmodel',
            name='associated_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
