# Generated by Django 3.2.5 on 2021-11-13 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_auto_20211113_1804'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Members',
        ),
    ]
