# Generated by Django 3.2.5 on 2021-12-10 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_alter_tournament_coorganisers'),
        ('clubs', '0002_elorating'),
    ]

    operations = [
    ]
