# Generated by Django 3.2.5 on 2021-12-11 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_auto_20211211_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='is_final',
            field=models.BooleanField(default=False),
        ),
    ]
