# Generated by Django 3.2.5 on 2021-11-27 01:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_clubapplicationmodel_associated_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='applicants',
            field=models.ManyToManyField(related_name='not_applicants', to=settings.AUTH_USER_MODEL),
        ),
    ]
