# Generated by Django 3.2.5 on 2021-12-15 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_auto_20211212_1609'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClubApplicationModel',
            new_name='ClubApplication',
        ),
    ]
