# Generated by Django 3.2.5 on 2021-12-11 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0004_tournament_is_final'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_number',
            field=models.IntegerField(),
        ),
    ]
