# Generated by Django 3.2.5 on 2021-11-28 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0004_club_applicants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubapplicationmodel',
            name='is_approved',
        ),
    ]
