# Generated by Django 3.2.5 on 2021-12-04 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0005_remove_clubapplicationmodel_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='elo_rating',
            field=models.IntegerField(default=1000),
        ),
    ]
