# Generated by Django 3.2.5 on 2021-12-03 22:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0005_remove_clubapplicationmodel_is_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('deadline', models.DateTimeField()),
                ('coorganisers', models.ManyToManyField(related_name='coorganises', to=settings.AUTH_USER_MODEL)),
                ('organiser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organises', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(related_name='participates_in', to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_wins', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('losers', models.ManyToManyField(blank=True, related_name='match_losses', to=settings.AUTH_USER_MODEL)),
                ('players', models.ManyToManyField(related_name='plays_in', to=settings.AUTH_USER_MODEL)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_within', to='clubs.tournament')),
                ('winner', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_wins', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
