# Generated by Django 3.2.5 on 2021-12-05 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0006_match_tournament'),
        ('clubs', '0006_user_elo_rating'),
    ]

    operations = [
    ]
