# Generated by Django 3.2.5 on 2021-12-08 22:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0006_auto_20211208_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='bye',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tournament',
            name='elimination_phase',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tournament',
            name='group_phase',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='round',
            field=models.IntegerField(default=1),
        ),
    ]
