# Generated by Django 3.2.5 on 2021-12-09 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0007_auto_20211208_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='elimination_phase',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='group_phase',
            field=models.BooleanField(default=False),
        ),
    ]
